# Generated by Django 5.0.3 on 2025-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
